name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: show files
      run: ls android
    - uses: actions/upload-artifact@v4.3.1
      with:
        # Artifact name
        name: artifact # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: android
    - uses: alexellis/upload-assets@0.4.1
      with:
        # The paths to the assets you want to upload as a JSON array. You can use a glob pattern.
        asset_paths: android
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
