name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: show files
      run: ls android
    - uses: nanoufo/action-upload-artifacts-and-release-assets@v2.0
      with:
      # A file or wildcard pattern that describes what to upload
        path: android
          
          
